In [1]:
import pandas as pd


In [5]:
df = pd.read_csv(" https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [6]:
df


,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551


In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[3]

np.int64(5)

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  5,  7, 12])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 100, 11 )

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [18]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
n_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
n_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
n_array[1]


array([4, 5, 6])

In [38]:
n_array[1,1] = 21

In [39]:
n_array

array([[ 1,  2,  3],
       [ 4, 21,  6],
       [ 7,  8,  9]])

In [40]:
n_array[2] = [7, 15, 21]

In [41]:
n_array

array([[ 1,  2,  3],
       [ 4, 21,  6],
       [ 7, 15, 21]])

In [43]:
n_array[:,2]

array([ 3,  6, 21])

In [44]:
n_array[:]

array([[ 1,  2,  3],
       [ 4, 21,  6],
       [ 7, 15, 21]])

In [45]:
n_array[:0] = [2002, 1994, 1970]

In [46]:
n_array

array([[ 1,  2,  3],
       [ 4, 21,  6],
       [ 7, 15, 21]])

In [48]:
np.random.rand(5,2)

array([[0.01154783, 0.9220886 ],
       [0.99027532, 0.98215422],
       [0.30416818, 0.13305054],
       [0.79148777, 0.76326991],
       [0.35646813, 0.50935266]])

In [49]:
np.random.seed(10)

In [54]:
np.random.randint(low=0, high=100, size=(5,2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

In [55]:
a = np.array([0,1,2,3,4])
a


array([0, 1, 2, 3, 4])

In [62]:
# element wise operations
b = 10 + (a *2) 
b

array([10, 12, 14, 16, 18])

In [61]:
a + b

array([10, 13, 16, 19, 22])

In [68]:
#comparison operations
filtro = a >= 2 
filtro

array([False, False,  True,  True,  True])

In [69]:
a[filtro]

array([2, 3, 4])

In [71]:
#summarizing operations
a.min()

np.int64(0)

In [72]:
a.max()

np.int64(4)

In [73]:
b.max()

np.int64(18)

In [74]:
b.std()

np.float64(2.8284271247461903)

In [75]:
b

array([10, 12, 14, 16, 18])

In [80]:
c = np.array([21,18,15,7])
c

array([21, 18, 15,  7])

In [81]:
d = c.sort()
d

In [7]:
#Vector - vector multiplication 
u = np.array([2,4,5,6])
ushape = u.shape
ushape

(4,)

In [8]:
v = np.array([1,0,0,2])
vshape = v.shape
vshape

(4,)

In [18]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0

    for i in range(n):
        result = result + u[i]*v[i]

    return result    




In [20]:
vector_vector_multiplication(u,v)

np.int64(14)